plugins { id 'com.android.application' }

android {
    namespace 'com.a14398138.fullscreenbrowser'
    compileSdk 35

    defaultConfig {
        applicationId 'com.a14398138.fullscreenbrowser'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
}
